# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


  lane :playstore do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
  end

  desc "Submit a new  Build to Play Store"
  lane :deploy do
    releaseFilePath = File.join(Dir.pwd, "../app", "keystore.jks")
    gradle(task: 'clean')
    keystore_store_password = "123456"
    keystoreStorePassword = "123456"
    puts "Keystore Store Password: #{keystoreStorePassword}"
    keystore_key_password = "123456"
    keystoreKeyPassword = "123456"
    puts "Keystore Key Password: #{keystoreKeyPassword}"
    gradle(
      task: 'bundle',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => "123456",
        "android.injected.signing.key.alias" => "key0",
        "android.injected.signing.key.password" => "123456",
      }
    )
    upload_to_play_store
  end
end
